### ISSUE TITLE
tiktok eror downloading

### ISSUE THREAD

**Issue by putraalm** [Kai0071/A17#70]
ReferenceError: A17Tiktok is not defined
    at A17 (/root/bot/A17/Core.js:4552:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot use 'in' operator to search for 'text' in ReferenceError: A17Tiktok is not defined
    at A17 (/root/bot/A17/Core.js:4552:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at generateWAMessageContent (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:214:16)
    at generateWAMessage (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:472:102)
    at Object.sendMessage (/root/bot/A17/node_modules/baileysjs/lib/Socket/messages-send.js:606:69)
    at A17 (/root/bot/A17/Core.js:6883:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) unhandledRejection
TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:41:67)
    at generateLinkPreviewIfRequired (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:45:48)
    at generateWAMessageContent (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:218:71)
    at generateWAMessage (/root/bot/A17/node_modules/baileysjs/lib/Utils/messages.js:472:102)
    at Object.sendMessage (/root/bot/A17/node_modules/baileysjs/lib/Socket/messages-send.js:606:69)
    at reply (/root/bot/A17/Core.js:301:17)
    at A17 (/root/bot/A17/Core.js:4550:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) unhandledRejection

**Comment by Kai0071** [comment]
Oke i will fix soon.
